run:
  timeout: 10m
  allow-serial-runners: true
linters-settings:
  goimports:
    local-prefixes: github.com/theopenlane/utils
  gofumpt:
    extra-rules: true
  gosec:
    exclude-generated: true
  revive:
    ignore-generated-header: true
linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gocyclo
    - err113
    - gofmt
    - goimports
    - mnd
    - gosimple
    - govet
    - gosec
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace
    - wsl
issues:
  fix: true
  exclude-use-default: true
  exclude-dirs:
    - totp/testing/*
  exclude-files:
    []
